version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'

  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'

  - package-ecosystem: 'npm'
    directory: '/packages/api'
    schedule:
      interval: 'daily'

  - package-ecosystem: 'npm'
    directory: '/packages/core'
    schedule:
      interval: 'daily'

  - package-ecosystem: 'npm'
    directory: '/packages/http'
    schedule:
      interval: 'daily'

  - package-ecosystem: 'npm'
    directory: '/packages/rest'
    schedule:
      interval: 'daily'

  - package-ecosystem: 'npm'
    directory: '/packages/types'
    schedule:
      interval: 'daily'

  - package-ecosystem: 'npm'
    directory: '/src/api'
    schedule:
      interval: 'daily'

  - package-ecosystem: 'npm'
    directory: '/packages/auth'
    schedule:
      interval: 'daily'

  - package-ecosystem: 'npm'
    directory: '/packages/graphql'
    schedule:
      interval: 'daily'

  - package-ecosystem: 'npm'
    directory: '/packages/handler'
    schedule:
      interval: 'daily'

  - package-ecosystem: 'npm'
    directory: '/packages/website'
    schedule:
      interval: 'daily'
