plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-berry.cjs

packageExtensions:
  '@chakra-ui/checkbox@*':
    dependencies:
      framer-motion: '>=3.0.0'
      react-dom: '>=17.0.0'
  '@chakra-ui/transition@*':
    dependencies:
      framer-motion: '>=3.0.0'
  '@chakra-ui/portal@*':
    dependencies:
      react-dom: '>=17.0.0'
  '@chakra-ui/radio@*':
    dependencies:
      react-dom: '>=17.0.0'
  '@chakra-ui/toast@*':
    dependencies:
      react-dom: '>=17.0.0'
  '@chakra-ui/system@*':
    dependencies:
      '@emotion/react': '>=11.0.0'
      '@emotion/styled': '>=11.0.0'
  '@chakra-ui/utils@*':
    dependencies:
      react: '>=17.0.0'
  '@reach/visually-hidden@*':
    dependencies:
      prop-types: '>=15.0.0'
  'zustand@*':
    dependencies:
      '@babel/runtime': '>=7.0.0'
