version: "3.7"

services:
  postgres:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: "yukikaze"
      POSTGRES_PASSWORD: "commander"
      POSTGRES_DB: "yukikaze_bot"
    volumes:
      - postgres-data-v1:/var/lib/postgresql/data
    expose:
      - "5432"
    restart: unless-stopped

  hasura:
      image: hasura/graphql-engine:v1.3.2.cli-migrations-v2
      expose:
        - "8080"
      ports:
        - "8080:8080"
      env_file:
        - ./.env
      restart: unless-stopped
      volumes:
        - ./migrations:/hasura-migrations

volumes:
  postgres-data-v1:
    name: "postgres-data-v1"
