table:
  name: guild_settings
  schema: public
array_relationships:
- name: moderators
  using:
    manual_configuration:
      column_mapping:
        guild_id: guild_id
      insertion_order: null
      remote_table:
        name: guild_moderators
        schema: public
insert_permissions:
- permission:
    backend_only: false
    check:
      moderators:
        _and:
        - user_id:
            _eq: X-Hasura-User-Id
        - manage:
            _eq: true
    columns:
    - guild_id
    - prefix
    - guild_log_channel_id
    - mod_log_channel_id
    - mod_role_id
    - member_log_channel_id
    - mute_role_id
    - tag_role_id
    - embed_role_id
    - emoji_role_id
    - reaction_role_id
    - locale
    - modules
  role: user
select_permissions:
- permission:
    allow_aggregations: true
    columns:
    - guild_id
    - prefix
    - guild_log_channel_id
    - mod_log_channel_id
    - mod_role_id
    - member_log_channel_id
    - mute_role_id
    - tag_role_id
    - embed_role_id
    - emoji_role_id
    - reaction_role_id
    - locale
    - modules
    filter:
      moderators:
        user_id:
          _eq: X-Hasura-User-Id
  role: user
update_permissions:
- permission:
    check:
      moderators:
        _and:
        - user_id:
            _eq: X-Hasura-User-Id
        - manage:
            _eq: true
    columns:
    - prefix
    - guild_log_channel_id
    - mod_log_channel_id
    - mod_role_id
    - member_log_channel_id
    - mute_role_id
    - tag_role_id
    - embed_role_id
    - emoji_role_id
    - reaction_role_id
    - locale
    - modules
    filter:
      moderators:
        _and:
        - user_id:
            _eq: X-Hasura-User-Id
        - manage:
            _eq: true
  role: user
